---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-kustomization

namespace: argocd

bases:
  - base/argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.5/manifests/install.yaml

patchesStrategicMerge:
  - overlays/argocd-server-deployment.yaml
  - overlays/argocd-application-controller-statefulset.yaml
