---
apiVersion: v1
kind: Service
metadata:
  name: tailscale
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 1055
      targetPort: proxy
      protocol: TCP
  selector:
    app: tailscale
