---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tailscale
  serviceName: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      securityContext: {}
      containers:
        - name: tailscale
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          image: ghcr.io/tailscale/tailscale:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1055
              name: proxy
          env:
            - name: TS_EXTRA_ARGS
              value: --accept-routes --hostname=kind-argocd-router
            - name: TS_KUBE_SECRET
              value: tailscale-state
            - name: TS_USERSPACE
              value: "true"
            - name: TS_SOCKS5_SERVER
              value: "0.0.0.0:1055"
            - name: TS_OUTBOUND_HTTP_PROXY_LISTEN
              value: "0.0.0.0:1055"
            - name: TS_ROUTES
              value: ""
            - name: TS_AUTH_KEY
              value: "${TAILSCALE_ROUTER_KEY}"
