---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  serviceName: argocd-application-controller
  template:
    spec:
      containers:
        - name: argocd-application-controller
          image: dinoshauer/argocd:2.5.5-1
          imagePullPolicy: IfNotPresent
